version: '3.8'

services:
  db:
    image: postgres:16
    container_name: eurostat_postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data

  etl:
    build: .
    container_name: eurostat_etl
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - .:/app
    command: >
      sh -c "
        echo 'Waiting for PostgreSQL...' &&
        sleep 10 &&
        echo 'Running ETL Pipeline...' &&
        python etl/main.py --mode full-refresh &&
        echo 'Generating Visualizations...' &&
        python viz/viz_utils.py
      "

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db

volumes:
  pgdata:
